# Taller 2

### Integrantes:
* Laura Sofia Fernandez | A00410462
* Juan Miguel Correa | A00412937
* Juan Jose Navas | A00411769
* Juan Camilo Libreros | A00412339

##1. Filtrar números primos

Escribe una función que reciba una lista de números y devuelva una nueva lista solo
con los números primos.

In [ ]:
import math

def es_primo(n): #Verificar si el numero es primo
    if n < 2:
        return False
    for i in range(2, int(math.sqrt(n)) + 1):
        if n % i == 0:
            return False
    return True

def main():
  lista = [2, 3, 4, 5, 6, 7, 8, 9, 10]
  lista_primos = []
  for i in lista:
    if es_primo(i):
      lista_primos.append(i)

  print(lista_primos)


if __name__ == "__main__":
  main()

[2, 3, 5, 7]


## 2. Escribe una función que reciba dos listas y devuelva una nueva lista con los elementos comunes entre ambas.

In [ ]:
def elementos_comunes(lista1, lista2):
    return list(set(lista1) & set(lista2))

def main():
  lista1 = [1, 2, 3, 4, 5]
  lista2 = [4, 5, 6, 7, 8]
  lista_comunes = elementos_comunes(lista1, lista2)
  print(lista_comunes)

if __name__ == "__main__":
  main()

[4, 5]


## 3. Crea una función que reciba una lista de números y la convierta en una matriz cuadrada. Si la cantidad de elementos no permite formar una matriz cuadrada, devuelve un mensaje de error.

In [ ]:
import math  # Falta importar math

def lista_a_matriz(lista):
    n = len(lista)
    raiz = math.sqrt(n)
    if raiz != int(raiz):
        return "Error: La cantidad de elementos no permite formar una matriz cuadrada."
    lado = int(raiz)
    matriz = [lista[i*lado:(i+1)*lado] for i in range(lado)]
    return matriz


def main():
    lista = [1, 7, 4, 7, 3, 8, 12, 4, 0]
    matriz = lista_a_matriz(lista)

    if isinstance(matriz, str):  # Si la función devolvió un error, imprimirlo directamente
        print(matriz)
    else:
        print("Matriz cuadrada:")
        for fila in matriz:
            print(fila)  # Imprime cada fila en una línea separada

if __name__ == "__main__":
    main()


Matriz cuadrada:
[1, 7, 4]
[7, 3, 8]
[12, 4, 0]


In [ ]:
import numpy as np

def lista_a_matriz(lista):
    n = len(lista)
    raiz = int(np.sqrt(n))

    if raiz != int(raiz):
        return "Error: La cantidad de elementos no permite formar una matriz cuadrada."

    return np.array(lista).reshape(raiz, raiz)

def main():
    lista = [1, 7, 4, 7, 3, 8, 12, 4, 0]
    matriz = lista_a_matriz(lista)

    if isinstance(matriz, str):
        print(matriz)
    else:
        print("Matriz cuadrada:\n", matriz)

if __name__ == "__main__":
    main()

Matriz cuadrada:
 [[ 1  7  4]
 [ 7  3  8]
 [12  4  0]]


## 4. Escribe una función que reciba una lista de números y devuelva la media, mediana y moda. Si hay más de una moda, devuelve todas.

In [ ]:
import numpy as np


def media(lista):
    return np.mean(lista)


def mediana(lista):
    return np.median(lista)

def moda(lista):
    valores, conteos = np.unique(lista, return_counts=True)  # Encuentra valores únicos y sus frecuencias
    max_frecuencia = np.max(conteos)  # Encuentra la frecuencia máxima
    modas = valores[conteos == max_frecuencia]  # Filtra los valores con la frecuencia máxima

    return modas if len(modas) > 1 else modas[0]  # Devuelve lista si hay varias modas

def main():
  lista = [1, 2, 3, 4, 5, 5, 6, 7, 8, 9, 10]

  print(round(media(lista), 2))
  print(mediana(lista))
  print(moda(lista))

if __name__ == "__main__":
  main()

5.45
5.0
5


## 5. Escribe una función que reciba una lista de precios de productos y una lista de cantidades compradas. La función debe calcular el total a pagar, aplicando un descuento del 10% si el total supera $100.

In [ ]:
def calcular_total(precios, cantidades):
    total = 0
    for i in range(len(precios)):
        total += precios[i] * cantidades[i]
    if total > 100:
        total *= 0.9
    return total

precios = [25, 30, 20, 15]
cantidades = [2, 1, 3, 4]
total_a_pagar = calcular_total(precios, cantidades)
print(f"Total a pagar: ${total_a_pagar:.2f}")


Total a pagar: $180.00


In [ ]:
import numpy as np

def descuento(Lista_precios,lista_cantidades):
  total = np.dot(Lista_precios,lista_cantidades)
  if total > 100:
    descuento = total * 0.10
    total_descuento = total - descuento
    return total_descuento
  else:
    return total

def main():
  Lista_precios = [25, 30, 20, 15]
  lista_cantidades = [2, 1, 3, 4]

  print(descuento(Lista_precios,lista_cantidades))

if __name__ == "__main__":
  main()

180.0


## 6. Control de inventario: Crea una función que reciba una lista de productos en inventario y una lista de productos vendidos. La función debe devolver una lista con los productos que quedan en inventario, eliminando los vendidos.



In [ ]:
def actualizado(inventario, vendidos):
    inventario_actualizado = []  # Crear una nueva lista
    for producto in inventario:
        if producto not in vendidos:
            inventario_actualizado.append(producto)
    return inventario_actualizado  # Devolver la lista actualizada

def main():
    # Listas de productos
    inventario = ["manzana", "banana", "pera", "uva", "naranja"]
    vendidos = ["banana", "uva"]

    # Llamar la función y obtener la lista actualizada
    inventario_actualizado = actualizado(inventario, vendidos)

    # Mostrar el inventario actualizado
    print("Inventario actualizado:", inventario_actualizado)

if __name__ == "__main__":
    main()

Inventario actualizado: ['manzana', 'pera', 'naranja']


## 7. Registro de temperaturas: Escribe una función que reciba una lista de temperaturas diarias (en grados Celsius) y devuelva cuántos días la temperatura estuvo por encima de 30°C, cuántos entre 20°C y 30°C, y cuántos por debajo de 20°C.

In [ ]:
def clasificar_temperaturas(temperaturas):
    dias_calidos = 0  # Más de 30°C
    dias_frios = 0  # Menos de 20°C
    dias_normales = 0  # Entre 20°C y 30°C (incluidos)

    for temperatura in temperaturas:
        if temperatura > 30:
            dias_calidos += 1
        elif 20 <= temperatura <= 30:
            dias_normales += 1
        else:
            dias_frios += 1

    return dias_calidos, dias_normales, dias_frios  # Retornamos los valores correctamente

# Lista de temperaturas de ejemplo
temperaturas = [15, 25, 35, 32, 2, 41, 30, 20, 22]

# Llamamos la función y almacenamos los resultados
dias_calidos, dias_normales, dias_frios = clasificar_temperaturas(temperaturas)

# Imprimimos los resultados correctamente
print(f"Días calurosos (>30°C): {dias_calidos}")
print(f"Días templados (20°C - 30°C): {dias_normales}")
print(f"Días fríos (<20°C): {dias_frios}")

## 8. Cálculo de calorías consumidas: Crea una función que reciba una lista de alimentos consumidos y una lista de calorías correspondientes a cada alimento. La función debe calcular el total de calorías consumidas y devolver un mensaje si se superan las 2000 calorías diarias recomendadas.

In [ ]:
import numpy as np

def caloria(lista_alimentos, lista_calorias):
    total_calorias = np.sum(lista_calorias)

    if total_calorias > 2000:
      return "Cuidado, estas comiendo muchas calorias"
    else:
      return "Estas comiendo bien"


def main():
  lista_alimentos = ["Hamburgueras", "Pan" , "Arroz", "Perro caliente", "Pizza"]
  lista_calorias = [600, 200, 300, 500, 1000]
  print(caloria(lista_alimentos, lista_calorias))


if __name__ == "__main__":
  main()

Cuidado, estas comiendo muchas calorias


## 9. Promedio de ventas mensuales: Escribe una función que reciba una lista de ventas mensuales (12 valores) y calcule el promedio de ventas. Además, debe indicar cuántos meses estuvieron por encima del promedio.


In [ ]:
def promedio_ventas(ventas):
    promedio_de_ventas = sum(ventas) / len(ventas)  # Usa 'ventas' en lugar de 'ventas_mensuales'
    meses_encima = sum(venta > promedio_de_ventas for venta in ventas)  # Usa 'ventas' en lugar de 'ventas_mensuales'

    return promedio_de_ventas, meses_encima


ventas_mensuales = [55, 150, 78, 62, 51, 29, 37, 43, 66, 102, 87]

# Llamamos a la función y guardamos los valores retornados
promedio, meses = promedio_ventas(ventas_mensuales)

# Imprimimos los resultados
print(f"Promedio de ventas: {promedio:.2f}")
print(f"Meses con ventas superiores al promedio: {meses}")


Promedio de ventas: 69.09
Meses con ventas superiores al promedio: 4



## 10. Sistema de descuentos en una tienda: Crea una función que reciba el total de una compra y aplique un descuento según el monto:
* 5% si el total está entre 50 y 100.
* 10% si el total es mayor a 100 y menor a 200.
* 15% si el total es mayor o igual a $200.
La función debe devolver el total con el descuento aplicado.

In [ ]:
def descuento_compra(total):
  if 50 <= total < 100:
    descuento=0.05
  elif 100< total <200:
    descuento=0.10
  elif 200<=total:
    descuento=0.15
  else:
    descuento=0


  total_con_descuento = total * (1 - descuento)
  return total_con_descuento


compra_total=float(input("Ingrese el tota de la compra: "))
print(f"Total con descuento: ${descuento_compra(compra_total):}")

## 11. Registro de pacientes: Escribe una función que reciba una lista de nombres de pacientes y una lista de edades. La función debe devolver una lista de pacientes mayores de 60 años, indicando que requieren atención prioritaria.


In [ ]:
def pacientes_prioritarios(nombres, edades):
    pacientes_mayores = [nombres[i] for i in range(len(edades)) if edades[i] > 60]

    return pacientes_mayores

nombres_pacientes = ["Ana", "Carlos", "Luis", "María", "Jorge"]
edades_pacientes = [45, 70, 61, 39, 80]

prioritarios = pacientes_prioritarios(nombres_pacientes, edades_pacientes)

print("Pacientes que requieren atención prioritaria:", prioritarios)


Pacientes que requieren atención prioritaria: ['Carlos', 'Luis', 'Jorge']


## 12. Cálculo de gastos mensuales: Crea una función que reciba una lista de gastos mensuales (alquiler, comida, transporte, etc.) y calcule el total de gastos. Además, debe indicar cuál fue el gasto más alto y en qué categoría se realizó.


In [ ]:
def gasto_total(gastos_mensuales):
    total_gastos = sum(gastos_mensuales.values())
    return total_gastos

def gasto_maximo(gastos_mensuales):
    gasto_maximo = max(gastos_mensuales, key=gastos_mensuales.get)
    return gasto_maximo

gastos_mensuales = {
    "Mercado" : 12.5,
    "Gym" : 150.0,
    "Salidas" : 600.0,
    "transporte" : 250.0,
    "salud" : 420.0
    }

print(f"total de gastos: {gasto_total(gastos_mensuales)}")
print(f"gasto maximo: {gasto_maximo(gastos_mensuales)}")

total de gastos: 1432.5
gasto maximo: Salidas


## 13. Control de asistencia a eventos: Escribe una función que reciba una lista de nombres de personas registradas para un evento y una lista de nombres de personas que asistieron. La función debe devolver una lista de personas que no asistieron.

In [ ]:
def personas_no_asistieron(registrados,asistieron):
  no_asistieron = set(registrados) - set(asistieron)
  return list(no_asistieron)

registrados=["Fabian","Andres","Laura","Julian","Patricia","Sara","Sofia"]
asistieron=["Laura","Sara","Sofia"]

no_asistieron=personas_no_asistieron(registrados,asistieron)
print(no_asistieron)

['Julian', 'Patricia', 'Fabian', 'Andres']


## 14. Recomendación de ejercicio diario:Crea una función que reciba la cantidad de minutos de ejercicio realizados en una semana (7 días) y devuelva un mensaje personalizado:

* "Excelente, estás en forma" si el promedio diario es mayor a 60 minutos.

* "Buen trabajo, pero puedes mejorar" si el promedio está entre 30 y 60 minutos.

* "Debes hacer más ejercicio" si el promedio es menor a 30 minutos

In [ ]:
def recomendacion_ejercicio(minutos_semanales):
  prom_minutos = minutos_semanales / 7

  if prom_minutos > 60:
    return "Excelente, estás en forma"
  elif 30 > prom_minutos < 60:
    return "Buen trabajo, pero puedes mejorar"
  else:
    return "Debes hacer más ejercicio"

minutos = int(input("Cantidad de minutos de ejercicio realizado en una semana: "))

print(recomendacion_ejercicio(minutos))

Cantidad de minutos de ejercicio realizado en una semana: 100
Buen trabajo, pero puedes mejorar
